### ISSUE TITLE
GnuPG-related options assume that "pinentry_mac" package is installed

### ISSUE THREAD

**Issue by seh** [midchildan/dotfiles#97]
In the _nix/home/modules/gnupg/default.nix_ file, there's [a binding for the "pinentry-mac" variable](https://github.com/midchildan/dotfiles/blob/1c190d0ac1d87c159b8b7d777f02261ae58a3fc5/nix/home/modules/gnupg/default.nix#L5) that reads the value of `pkgs.pinentry_mac`, referencing [the Nix package](https://search.nixos.org/packages?channel=23.05&show=pinentry_mac&from=0&size=50&sort=relevance&type=packages&query=pinentry_mac). However, I don't see anywhere else in this repository that ensures that the _pinentry\_mac_ package will be installed if we're using macOS and GnuPG is enabled.

[The _nix/home/news.nix_ file entry from December 2020](https://github.com/midchildan/dotfiles/blob/1c190d0ac1d87c159b8b7d777f02261ae58a3fc5/nix/home/news.nix#L73-L80) mentions a _dotfiles.pinentry-mac_ module, but I don't see such a module present today.

Do we need to mention the _pinentry\_mac_ project somewhere, such as in the _nix/home/profiles/essential.nix_ file, or maybe just in the _nix/home/modules/gnupg/default.nix_ file?

**Comment by midchildan** [comment]
The gnupg module that you referenced would actually work without any additional configuration. While pinentry_mac won't be available in `PATH` or `~/Applications`, it'll be present in the Nix store.

Here's a simplified version of the relevant configuration:

```nix
home.file.".gnupg/gpg-agent.conf".text = ''
  pinentry-program ${pkgs.pinentry_mac}/Applications/pinentry-mac.app/Contents/MacOS/pinentry-mac
'';
```

When Home Manager sees this, it builds a derivation similar to the following:

```nix
pkgs.writeTextFile {
  name = "gpg-agent.conf";
  text = ''
    pinentry-program ${pkgs.pinentry_mac}/Applications/pinentry-mac.app/Contents/MacOS/pinentry-mac
  '';
}
```

Nix sees that this derivation depends on `pkgs.pinentry_mac`, and instantiates it in the Nix store. `${pkgs.pinentry_mac}` is also replaced with the store path.

The key here is that there are other ways to use a package other than including it in `home.packages`.

**Comment by seh** [comment]
> Nix sees that this derivation depends on `pkgs.pinentry_mac`, and instantiates it in the Nix store. `${pkgs.pinentry_mac}` is also replaced with the store path.
> 
> The key here is that there are other ways to use a package other than including it in `home.packages`.

Oh, that was not apparent to me. Thank you for explaining that.

I'm not sure that I have any other reason to refer to the _pinentry-mac_ program other than for GnuPG to prompt me, so perhaps it being present but sort of "hidden" would be enough.

**Comment by midchildan** [comment]
The `dotfiles.pinentry-mac` module is something I used in the past to create a symlink to pinentry_mac in `/usr/local/bin`.

https://github.com/midchildan/dotfiles/blob/9128258ef19e93818b51fc7258aeb1152f7857bb/home/.config/nixpkgs/home.d/dotfiles/modules/pinentry-mac.nix

**Comment by seh** [comment]
I confirmed that yes, _pinentry-mac_ is available, in one case at a path like _/nix/store/h0j374ylb8g411sv9wnb55859v6fq2n2-pinentry-mac-1.1.1.1/Applications/pinentry-mac.app/Contents/MacOS/pinentry-mac_.
